export interface Whisky {
    idWhisky?: number,
    nomeWhisky?: string,
    idade?: string,
    dataCadastro?: string,
    teroAlcolico?: string,
    descricao_olfato?: string,
    descricao_paladar?: string,
    descricao_finalizacao?: string,
    idTipoWhisky?: number,
    idFabricante?: number,
    descricao_historica?: string,
    nacionalidade?: string,
    imagem?: string,
    descricao_barril?: string,
    nomeFabricante?: string,
    nomeTipoWhisky?: string,
  }